import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DeviceService } from '../../../services/device.service';
import { Device, DeviceType } from '../../../models/device.model';

@Component({
  selector: 'app-add-device',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './add-device.component.html',
  styleUrls: ['./add-device.component.css']
})
export class AddDeviceComponent {
  // Form model aligned with backend Device fields
  device: Omit<Device, 'id' | 'createdAt' | 'updatedAt'> = {
    deviceName: '',
    deviceType: DeviceType.COMPUTER as DeviceType,
    serialNumber: '',
    labName: '',
    status: 'Working',
    qrCodePath: ''
  };

  deviceTypes = Object.values(DeviceType);
  statuses: Array<Device['status']> = ['Working', 'Under Maintenance', 'Faulty'];

  message = '';
  loading = false;

  // ✅ New property to store the QR image URL
  qrImageUrl: string | null = null;

  constructor(private deviceService: DeviceService) {}

  onSubmit() {
    if (!this.device.deviceName || !this.device.serialNumber || !this.device.labName) {
      alert('Please fill all required fields.');
      return;
    }

    this.loading = true;
    this.device.qrCodePath = '';

    this.deviceService.create(this.device).subscribe({
      next: (response) => {
        this.loading = false;
        this.message = 'Device added successfully! QR code generated by backend.';

        // ✅ Add this line exactly here
        this.qrImageUrl = `http://localhost:8080${response.qrCodePath}`;

        console.log('Device saved:', response);
      },
      error: (err) => {
        this.loading = false;
        console.error(err);
        alert('Error saving device. Check backend connection.');
      }
    });
  }

  resetForm() {
    this.device = {
      deviceName: '',
      deviceType: DeviceType.COMPUTER,
      serialNumber: '',
      labName: '',
      status: 'Working',
      qrCodePath: ''
    };
    this.message = '';
    this.qrImageUrl = null; // clear the QR on reset
  }

  // ✅ Optional: download QR method
downloadQR() {
  if (!this.qrImageUrl) {
    alert('QR not available yet!');
    return;
  }

  fetch(this.qrImageUrl, {
    method: 'GET',
    headers: {
      'Content-Type': 'image/png',
    },
  })
    .then(response => {
      if (!response.ok) throw new Error('Failed to fetch QR');
      return response.blob();
    })
    .then(blob => {
      const a = document.createElement('a');
      const url = window.URL.createObjectURL(blob);
      a.href = url;
      a.download = `${this.device.deviceName}_QR.png`; // auto filename
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    })
    .catch(() => alert('Error downloading QR code'));
}
  }
